### ISSUE TITLE
Can't build progrium/busybox

### ISSUE THREAD

**Issue by devinrsmith** [progrium/busybox#15]
Similar to https://github.com/progrium/busybox/issues/14

```Shell
$ docker build -t progrium/busybox .
Sending build context to Docker daemon  6.96 MB
Sending build context to Docker daemon 
Step 0 : FROM scratch
Pulling repository scratch
511136ea3c5a: Download complete 
Status: Downloaded newer image for scratch:latest
 ---> 511136ea3c5a
Step 1 : MAINTAINER Jeff Lindsay <progrium@gmail.com>
 ---> Running in 3ff3b94b8917
 ---> 45092ce5d11f
Removing intermediate container 3ff3b94b8917
Step 2 : ADD ./rootfs.tar /
 ---> d23f67181c8e
Removing intermediate container 2d1ab9150a2d
Step 3 : ADD ./opkg.conf /etc/opkg.conf
 ---> bbeb12299b07
Removing intermediate container 2509eb5354a2
Step 4 : ADD ./opkg-install /usr/bin/opkg-install
 ---> 453ef30158f4
Removing intermediate container 151b22bf729b
Step 5 : ADD ./functions.sh /lib/functions.sh
 ---> 555191be6516
Removing intermediate container a2f0ff1a75c2
Step 6 : RUN opkg-cl install http://downloads.openwrt.org/snapshots/trunk/x86_64/packages/base/libgcc_4.8-linaro-1_x86_64.ipk
 ---> Running in 9b5014bad64c
wget: bad address 'downloads.openwrt.org'
Downloading http://downloads.openwrt.org/snapshots/trunk/x86_64/packages/base/libgcc_4.8-linaro-1_x86_64.ipk.
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/trunk/x86_64/packages/base/libgcc_4.8-linaro-1_x86_64.ipk, wget returned 1.
INFO[0049] The command [/bin/sh -c opkg-cl install http://downloads.openwrt.org/snapshots/trunk/x86_64/packages/base/libgcc_4.8-linaro-1_x86_64.ipk] returned a non-zero code: 255
```

**Comment by devinrsmith** [comment]
Working today!

**Comment by letitcrash** [comment]
@devinrsmith . Please let us know the solution for this issue. Thank You !

**Comment by devinrsmith** [comment]
I didn't change anything! I think one of the servers / repos must have been down.

**Comment by progrium** [comment]
Yep, that's usually the case. Switch to Alpine as noted in the readme.
Their package servers are much more reliable and has much more up to date
packages.

On Thu, Feb 19, 2015 at 1:46 PM, Devin Smith <notifications@github.com>
wrote:

> I didn't change anything! I think one of the servers / repos must have
> been down.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/busybox/issues/15#issuecomment-75122076>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by letitcrash** [comment]
Internally the container from progrium/busybox, the /etc/resolv.conf points to 172.17.42.1 as I overrode the /etc/default/docker filw with --dns 172.17.42.1.
Also I am able to ping downloads.openwrt.org from outside my container (on the host) successfully.
But when I login to the busybox container with "docker exec" and then do a "ping  downloads.openwrt.org" it says bad address. Insight appreciated.

**Comment by jtblin** [comment]
Had the same problem while tethering on my phone on Mac with boot2docker. Solve this by using `boot2docker ssh` to ssh into the VM host then edited `/etc/resolve.conf` to point `nameserver` to Google DNS: `8.8.8.8`. In case that helps someone else.
