### ISSUE TITLE
404 http://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/packages/Packages.gz. 

### ISSUE THREAD

**Issue by jarias** [progrium/busybox#19]
`opkg-cl -f /etc/opkg.conf update`

```
Downloading http://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/packages/Packages.gz.
wget: server returned error: HTTP/1.1 404 Not Found
```

Is not an direct image issue but I wonder if there are any other repos or mirrors?

**Comment by pires** [comment]
+1

@jarias `http://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/packages/`folder is gone.
Also, `bash` is no longer available :-(

/cc @antoniomeireles

**Comment by jarias** [comment]
URL is back online probably some maintenance work, should be nice to have a mirror somewhere maybe Bintray, I will look into this myself.

**Comment by progrium** [comment]
When I get back to this project, we'll likely put a CDN in front of the
repo. That should help cache on transient downtime and improve speed.

On Sun, Mar 29, 2015 at 11:42 AM, Julio Arias <notifications@github.com>
wrote:

> URL is back online probably some maintenance work, should be nice to have
> a mirror somewhere maybe Bintray, I will look into this myself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/busybox/issues/19#issuecomment-87439733>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by jarias** [comment]
@progrium Cool

**Comment by pires** [comment]
Any updates on this? Happening again :(

**Comment by pires** [comment]
Moved to http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/ ?

**Comment by pires** [comment]
Nevermind, new images work.
