### ISSUE TITLE
Perl downgrades libpthread

### ISSUE THREAD

**Issue by frol** [progrium/busybox#20]
I'm not sure where I should report this, but when I install perl (`opkg-install perl`) the `libpthread` package get installed which lead to this result in libs:

```bash
/ # ls -la /lib/libpthread*
-rwxr-xr-x    1 root     root         78593 Mar 29 04:49 /lib/libpthread-0.9.33.2.so
-rwxr-xr-x    1 root     root        141153 May 23  2014 /lib/libpthread-2.18.so
lrwxrwxrwx    1 root     root            22 May 29 14:08 /lib/libpthread.so.0 -> libpthread-0.9.33.2.so
```

Perl works fine, but other tools get segfaults.

I will hack it around with `LD_LIBRARY_PATH`, but if you think it is worthwhile to get fixed advise where we should report this.

**Comment by frol** [comment]
Here is my hack:

```Dockerfile
RUN opkg-install perl perlbase-ipc perlbase-getopt && \
    mkdir -p /opt/perl/lib && \
    mv /lib/libpthread-0.9.33.2.so /opt/perl/lib/ && \
    mv /lib/libpthread.so.0 /opt/perl/lib/ && \
    ln -s libpthread-2.18.so /lib/libpthread.so.0 && \
    rm /usr/bin/perl && \
    echo "LD_LIBRARY_PATH=/opt/perl/lib perl5.20.2" > /usr/bin/perl && \
    chmod +x /usr/bin/perl
```

**Comment by josh-padnick** [comment]
I actually ran into this same issue where `/lib/libpthread-0.9.33.2.so` was causing me problems.  In my case I ran `opkg-install bash wget python python-pip`, so I'm not sure who the culprit was.  Executing `ln -s libpthread-2.18.so /lib/libpthread.so.0` also fixed it for me.  Thanks for posting your solution @frol!

**Comment by progrium** [comment]
Thanks for the workaround.
