### ISSUE TITLE
/etc/init.d/ custom script not executed at boot

### ISSUE THREAD

**Issue by geertpeeters** [progrium/busybox#23]
I want to use this image to build an XAgent (www.xqual.com)
I managed to define the dockerfile in a correct way and everthing's there when I boot the docker image.
I added a script called S50xagent in /etc/init.d and made it executable.
However the script is not triggered by rcS. It seems that even rcS is not executed at all.
I added the command touch /tmp/thisworks to the rcS script, but after boot, there's nothing as such in the /tmp folder.
How can I launch an application at boot in this image? the xagent daemon script will register the docker image to the XStudio server instance.
manual launch of the script works fine. The agent shows up in the server instance...

**Comment by progrium** [comment]
These minimal container images are not designed to run full init systems. You'll have to figure that out yourself to run systems that require/assume an init system.
