### ISSUE TITLE
Future of progrium vs alpine

### ISSUE THREAD

**Issue by thockin** [progrium/busybox#24]
From the README:

>Notice: This image will probably soon be deprecated in favor of our even smaller Alpine Linux based image.

I would like to beg and plead not to do that.  There is a large need for utility containers that are not 75 or 100 MB in size. We need these things frequently in kubernetes, and as container orchestration becomes a dominant MO, everyone else will too.  Today, the best answer is to take Ubuntu (or debian or fedora or ...) And install one or two packages and bundled that as a container.

The fact that this produces hundreds of MB of image is ludicrous.

So why am I against Alpine?  The libc used therein is different enough from standard glibc so as to be useless.  The biggest example I hit whenever I try to use it is DNS.

Orchestrated environments like kubernetes DEPEND on DNS as a way to link services together at runtime.  This requires things like DNS search paths.

The Alpine folks seem totally uninterested in fixing this.  Please don't kill off progrium - it is the best platform I can find for building util containers.

I'm fact, I need to get a progrium package for 'dig' - does one exist?  I need a dnutils container!

What's the plan here?

**Comment by voidengineer** [comment]
+1

**Comment by progrium** [comment]
We've been experimenting with a glibc package in Alpine that lets you run glibc compiled binaries in Alpine. So far it works ok but if that doesn't pan out, then yes we'd keep this around.

**Comment by progrium** [comment]
Looks like OpenWRT just killed this image by switching to musl. Now all packages installed here no longer work and if we rebuilt the busybox image to use musl, you might as well use Alpine. Sucks, but OpenWRT just EOL'd this project. Best thing we could do is if somebody finds a repo mirror for older versions, but then we're stuck with old versions of what were already old versions ... forever.

**Comment by thockin** [comment]
And musl seems to have no intentions to fix their DNS

**Comment by progrium** [comment]
Maybe they're waiting somebody to patch it. 

Remind me what issue you're running into with musl DNS?

**Comment by thockin** [comment]
it ignores 'domain' and 'search' directives.  It also does parallel DNS
queries which is a bit surprising but not semantically invalid.

**Comment by progrium** [comment]
Right, but which specifically do you have problems with? We've had problems with parallel DNS because when having internal and external DNS, external DNS might resolve faster returning an NXDOMAIN for an internal name that exists. Honestly, I'm not a fan of this behavior, but apparently even glibc might start doing this. 

The problem you guys have is with search domains right?

Both of these can be fixed with something like dnsmasq on each host. In fact we made add support for `domain` and `search` to [Resolvable](https://github.com/gliderlabs/resolvable). But you work at Google ... maybe you can find a way to sponsor a patch to musl to support `domain` and `search`.

**Comment by thockin** [comment]
Yes, the problem we have is 'search'.  We rely on it.

As for parallel, I assumed, perhaps naively, that it would wait for all
responses if NXDOMAIN, and only short-circuit if it got a hit.  If not,
it's even MORE broken than I thought.

I think dnsmasq is not a search-domain expander (at least I can not find
how to do it).

As for fixing musl, you might think we are flush with people just sitting
around waiting for silly open-source bugs to fix, but it turns out not :)
 We're looking for any shortcut we can take, up to and including just
building trivial containers `FROM debian`.  Besides that I don't see any
indication that the musl folks want it fixed - I searched for threads and
it sounded like they thought it was a feature?!

**Comment by progrium** [comment]
We're adding search-domain expansion to Resolvable. Resolvable also:
 * fixes parallel searches
 * replaces Docker link-like local container name DNS resolution
 * allows for DNS servers/agents in containers to provide DNS to the host with zero-config

So that's our shortcut to patching musl. I was suggesting we could look into patching it as a bounty if Google could sponsor. Though from my experience, besides a few exceptions/programs, Google doesn't seem to do that often. 

Last thing to share is our glibc package for Alpine that installs glibc. It makes most glibc binaries Just Work, including Java 8 with a few extra modifications: https://github.com/andyshinn/alpine-pkg-glibc

**Comment by thockin** [comment]
Re: Bounty - yeah, I don't think we do that very often.  I would not even
know how to go about getting it set up.  We would certainly throw some
publicity and traffic your way just by talking about and using you, but I
know how much that is worth at the grocery store.

Re: glibc, that's a cute trick - how do I install that glibc into an Alpine
container - is there an apk for it?  Is there a source for alternative
implementations of apk packages that use proper libc?

**Comment by progrium** [comment]
We've been using the CircleCI build artifact with curl and then installing that apk file:
https://github.com/gliderlabs/docker-consul/blob/master/0.5/consul/Dockerfile#L3-L4

Looking into getting the package into Alpine packages, but it may require us to better improve the build process for it.

There isn't an index I know of for packages built glibc, this is primarily for existing or custom binaries that have already been compiled against glibc. It gets complicated with binaries with lots of dynamic library dependencies, but for Go binaries it's great. Most of the support packages we'd use are fine using musl.

**Comment by thockin** [comment]
@vmarmol

**Comment by mikedanese** [comment]
It seems that all installs of packages by opkg-install with progrium/busybox are now broken due to #25

**Comment by altvnk** [comment]
+1 To keep this. This container is very useful to run precompiled binaries with GLIBC.

**Comment by progrium** [comment]
If that's all you need does the more official busybox image work fine?

On Friday, July 31, 2015, Alexander Litvinenko <notifications@github.com>
wrote:

> +1 To keep this. This container is very useful to run precompiled binaries
> with GLIBC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/busybox/issues/24#issuecomment-126605174>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by discordianfish** [comment]
I just reverted another project to debian because of the alpine linux issues. Adding glibc to alpine also doesn't help if you depend on the alpine linux packages to use the search/domain features or the first nameserver first.

**Comment by thockin** [comment]
It sounds like the musl libc folks are willing to add search path support -
not sure what the timeline will be, but there is hope.

**Comment by discordianfish** [comment]
@thockin Do you happen to know what about the parallel dns resolution? The current behavior of that is also a blocker for me.

**Comment by thockin** [comment]
We're going to change the way we set up DNS to be more compatible with the
way they do lookups.  We discussed it at length and, despite no real spec
existing, we agreed it would be "more compatible".

**Comment by mhart** [comment]
Just in case this had slipped past people – it's been on musl's radar for a while and is currently slated to be tackled in 1.1.13: https://github.com/gliderlabs/docker-alpine/issues/8#issuecomment-174977774

**Comment by thockin** [comment]
Actually I saw that search path support has been merged into musl.  Not
sure how long that will take to propagate up to alpine and into a docker
image, but there's hope.

**Comment by h0tbird** [comment]
I use `go-dnsmasq` in the host. It takes care of expansion.

**Comment by thockin** [comment]
@artfulcoder another option for DNS caching :)
