### ISSUE TITLE
instalation of any new package returns not found

### ISSUE THREAD

**Issue by Andre-Freitas** [progrium/busybox#25]
If i try to use your image and try to install curl i can't use it because it doesn't find it. what could be causing this?

$ docker run -it progrium/busybox
latest: Pulling from progrium/busybox
12e04e1c69a0: Pull complete 
6132ea3e0902: Pull complete 
e164831a78af: Pull complete 
870fd05019ef: Pull complete 
91288b3d4258: Pull complete 
5c7a78d9845e: Pull complete 
87b9b6f4924b: Pull complete 
27c9295ee056: Already exists 
Digest: sha256:e375c6cf80ba13c63de289f63ccf244cade12df795cec95788903f240457c717
Status: Downloaded newer image for progrium/busybox:latest
/ # opkg-install curl
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz.
Inflating http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/base.
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz.
Inflating http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/packages.
Installing curl (7.40.0-3) to root...
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/curl_7.40.0-3_x86_64.ipk.
Installing libcurl (7.40.0-3) to root...
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/libcurl_7.40.0-3_x86_64.ipk.
Installing libpolarssl (1.3.11-1) to root...
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/libpolarssl_1.3.11-1_x86_64.ipk.
Configuring libpolarssl.
Configuring libcurl.
Configuring curl.
/ # curl
/bin/sh: curl: not found

**Comment by progrium** [comment]
Well it's there. Try:

```
ls -la /usr/bin/curl
```

So all I can say is it's an upstream issue. Pretty much every issue with
this image is going to be an upstream issue.

On Tue, Jun 30, 2015 at 8:05 AM, Andre-Freitas <notifications@github.com>
wrote:

> If i try to use your image and try to install curl i can't use it because
> it doesn't find it. what could be causing this?
>
> $ docker run -it progrium/busybox
> latest: Pulling from progrium/busybox
> 12e04e1c69a0: Pull complete
> 6132ea3e0902: Pull complete
> e164831a78af: Pull complete
> 870fd05019ef: Pull complete
> 91288b3d4258: Pull complete
> 5c7a78d9845e: Pull complete
> 87b9b6f4924b: Pull complete
> 27c9295ee056: Already exists
> Digest:
> sha256:e375c6cf80ba13c63de289f63ccf244cade12df795cec95788903f240457c717
> Status: Downloaded newer image for progrium/busybox:latest
> / # opkg-install curl
> Downloading
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz
> .
> Inflating
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz
> .
> Updated list of available packages in /var/opkg-lists/base.
> Downloading
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz
> .
> Inflating
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz
> .
> Updated list of available packages in /var/opkg-lists/packages.
> Installing curl (7.40.0-3) to root...
> Downloading
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/curl_7.40.0-3_x86_64.ipk
> .
> Installing libcurl (7.40.0-3) to root...
> Downloading
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/libcurl_7.40.0-3_x86_64.ipk
> .
> Installing libpolarssl (1.3.11-1) to root...
> Downloading
> http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/libpolarssl_1.3.11-1_x86_64.ipk
> .
> Configuring libpolarssl.
> Configuring libcurl.
> Configuring curl.
> / # curl
> /bin/sh: curl: not found
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/progrium/busybox/issues/25>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by Andre-Freitas** [comment]
yes i know that its there in /usr/bin/curl the problem is that even if i try to run it still gives 
sh: /usr/bin/curl: not found

When you says that is an upstrem problem is from upstream busybox or upstream openwrt?

**Comment by progrium** [comment]
The package is from openwrt. I'd file a bug there or look at their commit history. As far as I know, this can happen when something is compiled against wrong system libraries. The openwrt package index is not known for being terribly reliable as this image has shown. Perhaps look at alpine.

**Comment by progrium** [comment]
It looks like they switched to musl, which is what Alpine uses. In order to make packages work again, we'd have to rebuild busybox to use musl ... but then you might as well use Alpine. That's currently the only reason not to use Alpine and OpenWRT just killed it.

**Comment by a86c6f7964** [comment]
Does this mean that this image is now basically useless?

**Comment by progrium** [comment]
I believe so. Unless something major happens. Maybe somebody can find another opkg repo we can use? Maybe somebody can make one? I certainly can't right now.
