### ISSUE TITLE
Need ssh

### ISSUE THREAD

**Issue by timcrall** [progrium/busybox#28]
When I install git and try to clone via ssh, I get an error:

error: cannot run ssh: No such file or directory
fatal: unable to fork

There is no ssh client installed on the image.  Googling around, I have not found an easy way to install a ssh client.  (Dropbear seems to be what everyone points to, but that seems to require compiling, which requires make, which is also not installed, and so on...)

Is there an easy way to add ssh capability to this image so that git can actually be used?

Note: trying git with an http url also gives an error, "Unable to find remote helper for 'http'" - but in any event, I really need to be able to use ssh...

**Comment by jackwilsdon** [comment]
You can enable support for HTTP(s) URLs by installing `git-http` instead of  `git`;

```Shell
$ opkg-install git-http
$ git clone https://github.com/progrium/busybox.git # as an example
```

You can get SSH working too by installing `openssh-client` and linking the installed SSH binary to `/usr/bin/ssh`;

```Shell
$ opkg-install git-http openssh-client
$ ln -s /usr/bin/openssh-ssh /usr/bin/ssh
$ git clone git@github.com:progrium/busybox.git # as an example
```
