### ISSUE TITLE
Getting 404:- with opkg-install libseccomp ca-certificates

### ISSUE THREAD

**Issue by udkumar** [progrium/busybox#29]
Step 3/6 : RUN opkg-install libseccomp ca-certificates
 ---> Running in 9b0a50cd23a5
wget: server returned error: HTTP/1.1 404 Not Found
wget: server returned error: HTTP/1.1 404 Not Found
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz.
Downloading http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz.
Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/Packages.gz, wget returned 1.
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/packages/Packages.gz, wget returned 1.
Unknown package 'libseccomp'.
Unknown package 'ca-certificates'.
Collected errors:
 * opkg_install_cmd: Cannot install package *libseccomp*.
 * opkg_install_cmd: Cannot install package *ca-certificates*.

**Comment by jackwilsdon** [comment]
Looks like this is an issue with OpenWRT's repositories, as those files should definitely be there (you can even see the listings in Google search right now). Had a look on their forum and couldn't find any posts about it — maybe it's worth you posting something there too?

**Comment by udkumar** [comment]
Thanks @jackwilsdon

**Comment by typekpb** [comment]
@udkumar a bit unrelated but, I used to use the `ca-certificates` in the past as well, currently I've seen better results with `ca-bundle`
